apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiscal-dash-staging
spec:
  destination:
    name: ''
    namespace: fiscal-ns-staging
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/app/prd
    repoURL: 'https://github.com/danlhennessy/fiscal-dash'
    targetRevision: master
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
