apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginxlabel
  type: LoadBalancer
  externalIPs:
    - 192.168.0.10
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80