apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netshoot
spec:
  destination:
    name: 'sandboxcluster'
    namespace: default
    server: ''
  source:
    path: Kubernetes/manifests/netshoot
    repoURL: 'https://github.com/danlhennessy/homelab-k8s'
    targetRevision: HEAD
  sources: []
  project: default
