apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-backend
  target:
    name: secret-to-be-created
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: example-op
    remoteRef:
      key: example-op/d5c0a1e6f7a14b63865f685ad344a40f

  # explicit type and name of secret in the Azure KV
  - secretKey: clientID
    remoteRef:
      key: clientID