apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
spec:
  destination:
    name: ''
    namespace: nginx-ingress
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/manifests/nginx-basic/ingress/controller
    repoURL: 'https://github.com/danlhennessy/homelab-k8s'
    targetRevision: HEAD
  sources: []
  project: default
