apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  labels:
    aks-cluster-label: ok
    aks-subnet: ok
  name: aks-subnet
spec:
  forProvider:
    addressPrefixes:
      - 10.0.1.0/24
    resourceGroupNameSelector:
      matchLabels:
        aks-cluster-label: ok
    virtualNetworkNameSelector:
      matchLabels:
        aks-cluster-label: ok