apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter2
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  template:
    metadata:
      labels:
        app: kube-hunter2
    spec:
      containers:
        - name: kube-hunter2
          image: aquasec/kube-hunter:0.6.8
          command: ["kube-hunter"]
          args: ["--interface"]
      restartPolicy: Never