apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  template:
    metadata:
      labels:
        app: kube-hunter
    spec:
      containers:
        - name: kube-hunter
          image: aquasec/kube-hunter:0.6.8
          command: ["kube-hunter"]
          args: ["--pod"]
      restartPolicy: Never