apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: trivy-scan
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  entrypoint: trivy-scan
  templates:
    - name: trivy-scan
      container:
        image: aquasec/trivy:latest
        command: [trivy]
        args:
          - k8s
          - --report
          - summary
          - all
          # - --all-namespaces
