apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/manifests/MySQL
    repoURL: 'https://github.com/danlhennessy/homelab-k8s'
    targetRevision: HEAD
  sources: []
  project: default
