apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: Argo-Workflows
    repoURL: 'https://github.com/danlhennessy/homelab-k8s'
    targetRevision: HEAD
  sources: []
  project: default
  patch:
    - target:
        kind: Deployment
        name: argo-server
      patch: |
        - op: replace
          path: /spec/template/spec/containers/0/args
          value:
            - server
            - --auth-mode=server