apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: very-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: silly
  serviceAccountName: workflow
  templates:
  - name: silly
    container:
      image: alpine:latest
      command: [ls]
      args: ["-l"]