apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert
  namespace: default
spec:
  dnsNames:
    - subdomain1.domain.com
    - subdomain2.domain.com
    - subdomain.example.domain.com
  secretName: distil-cert
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer