apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-basic-staging
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/nginx-basic/staging
    repoURL: 'https://github.com/danlhennessy/homelab-k8s'
    targetRevision: HEAD
  sources: []
  project: default
