apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  commonName: k.danlhennessy.com
  dnsNames:
  - k.danlhennessy.com