apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-set
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/danlhennessy/homelab-k8s.git
      revision: HEAD
      directories:
      - path: Kubernetes/manifests/appset/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/danlhennessy/homelab-k8s.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: sandboxcluster
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true