apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kubectl-get-pods-
  namespace: argo
spec:
  serviceAccountName: argo-admin
  entrypoint: kubectl-get-pods
  templates:
    - name: kubectl-get-pods
      container:
        image: bitnami/kubectl:latest
        command: [kubectl]
        args: [get, pods, -n, default]
